version: '3.2'

# Note that trying to add the warc-base jar in ahead of time seems to cause issues with JAR-hell verison conflicts.

services:

  jupyter:
    image: jupyter/all-spark-notebook
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.base_url=/ukwa/jupyter"
    ports:
      - "8889:8888"
    volumes:
      - /data:/home/jovyan/data
      - /mnt/gluster/wa/:/home/jovyan/report-data
      - /root/github/ukwa-manage:/home/jovyan/ukwa-manage
      - /var/task-state:/home/jovyan/task-state

