
version: "3.2"

services:

  # Web page rendering service
  wrender-worker:
    image: ukwa/webrender-phantomjs:2.0.8
    environment:
      - "LC_ALL=en_US.utf8"
      - "TMP=/tmp/webrender"
      - "SERVICE_PORTS=8010"
      - "HTTP_PROXY=http://fwd-proxy:3128"
    networks:
      - wrendernet
    deploy:
      replicas: 3
#- "WARCPROX=warcprox:8000"

  # HAProxy load balancer
  wrenderfarm:
    image: dockercloud/haproxy
    ports:
      - "8011:80"
      - "1936:1936"
    environment:
      - "BALANCE=roundrobin"
      - "TIMEOUT=connect 10s, client 1m, server 1m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wrendernet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # Proxy to the outside world (because only some nodes have access)
  fwd-proxy:
    image: sameersbn/squid
    ports:
      - "3128:3128"
    volumes:
      - /data/test/squid-cache:/var/spool/squid3
    networks:
      - wrendernet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == crawler02

networks:
  wrendernet:
    driver: overlay

