
version: '2'

services:

  # PhantomJS web page rendering service
  wrender-worker:
    image: ukwa/webrender-phantomjs:2.0.4
    environment:
      - "WARCPROX=warcprox:8000"
      - "LC_ALL=en_US.utf8"
      - "TMP=/tmp/webrender"
    links:
      - warcprox

  # HAProxy load balancer
  wrenderfarm:
    image: dockercloud/haproxy
    ports:
      - "8010:80"
      - "1936:1936"
    environment:
      - BALANCE=roundrobin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - wrender-worker
