version: "3.2"

services:
  # ----------------------------------------------
  # UKWA Heritrix
  # ----------------------------------------------
  heritrix-worker:
    image: ukwa/heritrix-worker:2.2.12
    hostname: "h3-{{.Task.Slot}}"
    environment:
      - "JAVA_OPTS=-Xmx4g"
      - "MAX_TOE_THREADS=100"
      - "CLAMD_HOST=clamd"
      - "CLAMD_ENABLED=true"
      - "KAFKA_BOOTSTRAP_SERVERS=${EXTERNAL_HOSTNAME}:9094"
      - "KAFKA_CRAWLED_TOPIC=uris.crawled.dc"
      - "KAFKA_TOCRAWL_TOPIC=uris.tocrawl.dc"
      - "KAFKA_CANDIDATES_TOPIC=uris.tocrawl.dc"
      - "KAFKA_CANDIDATES_IN_SCOPE_ONLY=true"
      - "KAFKA_DISCARDED_FEED_ENABLED=false"
      - "KAFKA_DISCARDED_TOPIC=uris.discarded.dc"
      - "KAFKA_CONSUMER_ID={{.Task.Slot}}"
      - "KAFKA_CONSUMER_GROUP_SIZE=16" # NOTE this MUST be the same as the number of replicas below!
      - "KAFKA_SEEK_TO_BEGINNING=false" # To set to false if we try to re-use the state folders, to cope with the size of the tocrawl feed.
      - "KAFKA_MAX_POLL_RECORDS=1000"
      - "KAFKA_NUM_MESSAGE_THREADS=16"
      - "RECORD_DECIDING_RULE=true"
      - "WRENDER_ENDPOINT=http://wrender:8010/render"
      - "WEBRENDER_ENABLED=false" # Don't render web-pages from within Heritrix for this crawl
      - "CDXSERVER_ENDPOINT=http://192.168.45.21:9090/dc-2018-1"
      - "MAX_OUTBACKCDX_CONNECTIONS=500"
      - "CRAWL_NAME=domain"
      - "HERITRIX_USER=admin"
      - "HERITRIX_PASSWORD=bl_uk"
      - "LAUNCH_AUTOMATICALLY=false"
      - "PAUSE_AT_START=true"
      # Scope changes to make this a Domain Crawl:
      - "SURTS_SOURCE_FILE=/shared/dc-surts.txt" # Use the domain SURT scope
      - "SCOPE_FILE_RELOAD_INTERVAL=60"
      - "GEOIP_GB_ENABLED=true" # Also allow GeoIP-based inclusion (GB is in scope)
      - "USER_AGENT_PREFIX=bl.uk_lddc_bot" # Also declare a different User Agent for this crawl.
      # Use hop depth to control the domain crawl:
      - "MAX_HOPS_DEFAULT=20"
    volumes:
      - /data/dc/heritrix/output:/heritrix/output
      - /data/dc/heritrix/state:/heritrix/state # Store state outside to avoid overloading the container - the hostname is used to keep different runs separate.
      - /data/dc/surts:/shared # Shared configuration - surts file held here.
      - type: tmpfs
        target: /heritrix/scratch # Use RAM disk for scratch space.
    deploy:
      replicas: 16
    stop_grace_period: 2m # Give the H3 instances some time to shut down neatly following SIGTERM
    depends_on:
      - kafka-1
      - kafka-2
      - clamd

  # ----------------------------------------------
  # Clamd virus scanning service
  # ----------------------------------------------
  clamd:
    image: ukwa/clamd
    deploy:
      replicas: 16


