version: '2'

services:
  # W3ACT
  w3act:
    build: w3act
    ports:
      - "9000:9000"
    volumes:
      - ~/.ivy2/:/root/.ivy2/ # Mount the Ivy2 dependencies cache so it doesn't take forever to get going every time, downloading dependencies
    links:
      - openwayback
      - pdf2htmlex
  #    - postgres

  # UKWA Heritrix
  ukwa-heritrix-lbs:
    image: ukwa/ukwa-heritrix-lbs
    #hostname: ukwa-h3-fc
    ports:
      - "8443:8443"
    environment:
      - "MONITRIX_ENABLED=1"
    links:
      - clamd
      - amqp
      - webrender
    volumes_from:
      - dvc:rw  

  # Other daemons and processes that coordinate the crawl
  shepherd:
    build: python-shepherd
    environment:
      - "AMQP_URL=amqp://guest:guest@amqp:5672/%2f"
      - "QUEUE_NAME=FC-4-uris-to-index"
      - "CDXSERVER_URL=http://cdxserver:8080/fc"
      - "W3ACT_URL=http://w3act:9000/act/"
      - "W3ACT_USER=wa-sysadm@bl.uk"
      - "W3ACT_PW=sysAdmin"
      - "WAYBACK_URL=http://openwayback:8080/wayback"
      - "PYTHONUNBUFFERED=TRUE"
    links:
      - amqp
      - ukwa-heritrix-lbs
      - webrender
      - w3act
      - monitrix
    ports:
      - "5001:8000"
      - "5082:8082"
    volumes_from:
      - dvc:rw  

  # Data Volume Container for crawler job definitions and outputs
  dvc:
    image: busybox
    volumes:
      - ./testing/heritrix/output:/heritrix/output
      - ./testing/heritrix/wren:/heritrix/wren
      - ./testing/jobs:/jobs

  # Clamd virus scanning Service
  clamd:
    image: ukwa/clamd
    ports:
      - "3310:3310" 

  # Monitrix, built on ELK by extending Logstash to support Heritrix logs.
  monitrix:
    image: ukwa/monitrix
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5000:5000"
      - "5044:5044" 

  # RabbitMQ
  amqp:
    image: rabbitmq:3.5-management
    ports:
      - "15672:15672"  # management port (guest:guest)
      - "5672:5672"   # amqp port
      - "25672:25672" # cluster port
    logging:
      driver: none  

  # PhantomJS web page rendering service
  webrender:
    build: webrender-phantomjs
    environment:
      - "PHANTOMJS_BINARY=/opt/phantomjs/bin/phantomjs"
      - "WARCPROX=warcprox:8000"
    ports:
      - "8010:8010"
    links:
      - warcprox

  # WARC Proxy, with de-duplication disabled and a rapid rollover:
  warcprox:
    image: ukwa/warcprox
    command: "warcprox -b 0.0.0.0 -d /heritrix/wren --base32 -z --rollover-idle-time 60 -j /dev/null"
    ports:
      - "8000:8000"
    ulimits:
      nproc: 65535 # We need to set this, because the default is '-1' which warcprox uses and then *no threads* are created!
    volumes_from:
      - dvc:rw  
  
  # PDF to HTML service
  pdf2htmlex:
    image: ukwa/pdf2htmlex
    links:
      - openwayback
  #  ports:
  #    - "5000:5000"


