version: "3.2"

services:
  # UKWA Heritrix
  heritrix-worker:
    image: ukwa/heritrix-worker:2.4.7
    hostname: "heritrix3-worker-{{.Task.Slot}}"
    ports:
      - 8443:8443
    environment:
      - "JAVA_OPTS=-Xmx4g"
      - "MAX_TOE_THREADS=400"
      - "CLAMD_HOST=clamd"
      - "CLAMD_ENABLED=true"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "KAFKA_TOCRAWL_TOPIC=fc.candidates"
      - "KAFKA_CANDIDATES_TOPIC=fc.candidates"
      - "KAFKA_CANDIDATES_LOG_ENABLED=false"
      - "KAFKA_CANDIDATES_IN_SCOPE_ONLY=true"
      - "KAFKA_CRAWLED_TOPIC=fc.crawled"
      - "KAFKA_SEEK_TO_BEGINNING=true"
      - "KAFKA_MAX_POLL_RECORDS=1000"
      - "KAFKA_NUM_MESSAGE_THREADS=16"
      - "RECORD_DECIDING_RULE=true"
      - "WEBRENDER_ENDPOINT=http://webrender:8010/render"
      - "WEBRENDER_ENABLED=true"
      - "CDXSERVER_ENDPOINT=http://192.168.45.21:9090/fc"
      - "JOB_NAME=frequent"
      - "HERITRIX_USER=admin"
      - "HERITRIX_PASSWORD=bl_uk"
      - "LAUNCH_AUTOMATICALLY=true"
      - "CHECKPOINT_FORGET_ALL_BUT_LATEST=false"
      # Crawl scope main configuration - gets updated as seeds are launched, or can up updated externally:
      - "SURTS_SOURCE_FILE=/shared/frequent-surts.txt" # Use shared surts file.
      - "SURTS_EXCLUDE_SOURCE_FILE=/shared/frequent-excluded-surts.txt" # Use shared exclusion file.
      - "SCOPE_FILE_RELOAD_INTERVAL=60"
      - "WARC_PREFIX=BL-NPLD"
      - "WEBRENDER_WARC_PREFIX=BL-NPLD-WEBRENDER"
    volumes:
      - "/mnt/gluster/fc/heritrix/output:/heritrix/output"
      - "/mnt/gluster/fc/heritrix/state:/heritrix/state"
      - "/mnt/gluster/fc/surts:/shared" # Shared configuration - surts file held here.
    deploy:
      replicas: 1
    depends_on:
      - clamd
      - webrender

  # Clamd virus scanning Service
  clamd:
    image: ukwa/clamd
    deploy:
      replicas: 4

  # ----------------------------------------------
  # WARC Proxy
  # ----------------------------------------------

  # The WARChiving proxy itself
  warcprox:
    image: ukwa/warcprox:2.3.1
    command: "warcprox -b 0.0.0.0 -d /output/warcs --base32 --gzip --rollover-idle-time 600 --dedup-db-file /dev/null --stats-db-file /dev/null --quiet --plugin warcprox-plugins.listeners.UpdateOutbackCDX --plugin warcprox-plugins.listeners.KafkaCaptureFeed"
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=192.168.45.19:9094"
      - "KAFKA_CRAWLED_TOPIC=fc.crawled"
      - "KAFKA_ACKS=1"
      - "CDXSERVER_ENDPOINT=http://192.168.45.21:9090/fc"
    volumes:
      - "/mnt/gluster/fc/heritrix/wren:/output/warcs"
    deploy:
      replicas: 1


  # ----------------------------------------------
  # Web Render Farm
  # ----------------------------------------------

  # PhantomJS web page rendering service
  webrender:
    image: ukwa/webrender-phantomjs:2.0.14
    ports:
      - 8010:8010
    environment:
      - "WARCPROX=warcprox:8000"
      - "LC_ALL=en_US.utf8"
      - "TMP=/tmp/webrender"
    volumes:
      - type: tmpfs
        target: /tmp/webrender
      - "./webrender-gunicorn.ini:/webrender/gunicorn.ini" # Override render server configuration
    deploy:
      replicas: 1
    depends_on:
      - warcprox


  # ----------------------------------------------
  # Monitoring
  # ----------------------------------------------

  prometheus:
    image: prom/prometheus
    ports:
      - 9191:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - "/mnt/gluster/fc/prometheus-data:/prometheus"
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://crawler02.bl.uk:9191/'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'


