version: '3.2'

services:
  # OpenWayback for QA
  openwayback:
    image: ukwa/waybacks
    ports:
      - "9080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=qa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"
      - "WAYBACK_URL_PREFIX=${W3ACT_SERVER_NAME}/act"
      - "WAYBACK_URL_HOST=${INTERNAL_IP}"

  # PDF to HTML service
  pdf2htmlex:
    image: ukwa/pdf2htmlex:1.0.1
    ports:
      - "5005:5000"
    depends_on:
      - openwayback

  # W3ACT
  w3act:
    image: ukwa/w3act:${W3ACT_VERSION}
    environment:
      - "APPLICATION_SECRET=${APPLICATION_SECRET}"
      - "SECRET_SERVER_USER=${SECRET_SERVER_USER}"
      - "SECRET_SERVER_PASSWORD=${SECRET_SERVER_PASSWORD}"
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URI=postgres://w3act:${W3ACT_PSQL_PASSWORD}@postgres/w3act"
      - "USE_TEST_DATA=false"
      - "ENABLE_DDHAPT=true"
      - "SMTP_SERVER=juno.bl.uk"
      - "WAYBACK_URL=http://openwayback:8080/wayback"
      - "MONITRIX_URI=http://monitrix:5601/app/kibana"
      - "PDFTOHTMLEX_URI=http://pdf2htmlex:5000/convert?url="
      - "AMQP_HOST=amqp"
      - "SERVER_NAME=${W3ACT_SERVER_NAME}"
      - "PII_URI=${PII_URL}"
      - "ACCESS_RESOLVER_URI=https://www.webarchive.org.uk/access/resolve/"
      - "ENABLE_EVOLUTIONS=false"
      - "APPLY_EVOLUTIONS=false"
      - "APPLY_DOWN_EVOLUTIONS=false" # WARNING DOWNS ARE POTENTIALLY DESTRUCTIVE
    volumes:
      - "${DDHAPT_SIPS_SUBMITTED_DIR}:/opt/data/dls_sips_copy"
      - "${DDHAPT_EBOOKS_SUBMISSION_DIR}:/opt/data/w3act/ebooks:shared"
      - "${DDHAPT_EJOURNALS_SUBMISSION_DIR}:/opt/data/w3act/ejournals:shared"
    ports:
      - "9000:9000"
    depends_on:
      - openwayback
      - pdf2htmlex
    extra_hosts:
      - "blsps.ad.bl.uk:194.66.238.125"
      - "pii.ad.bl.uk:172.16.101.47" 
      - "v8b-dlsebk01.ad.bl.uk:192.168.242.115"
      - "v8b-dlseco01.ad.bl.uk:192.168.242.107"
      - "piiirc.ad.bl.uk:192.168.225.236"
      - "crawler03.bl.uk:127.0.0.1"

  # PostgreSQL
  postgres:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=w3act"
      - "POSTGRES_PASSWORD=${W3ACT_PSQL_PASSWORD}"
    ports:
      - "5433:5432"
    volumes:
      - "${W3ACT_PSQL_DIR}:/var/lib/postgresql/data"



