# This override file augments the base configuration with the additional configuration that distingiuishes different deployments
#
# The settings below are for the 'beta' service.
#
services:

  # Integration points:
  shepherd:
    environment:
      - "CDXSERVER_URL=http://192.168.45.21:8080/beta-data-heritrix"
      - "HDFS_OUTPUT_PREFIX=/beta"
      - "HDFS_NAMENODE_HOST=194.66.232.90"
      - "HDFS_NAMENODE_PORT=50070"
      - "HDFS_EFFECTIVE_USER=heritrix"
      - "WEBHDFS_PORT=14000"
      - "WEBHDFS_USER=heritrix"
      - "WEBHDFS_PREFIX=http://194.66.232.90:14000/webhdfs/v1/beta"

  openwayback:
    environment:
      - "WAYBACK_HTTPFS_PREFIX=http://194.66.232.90:14000/webhdfs/v1/beta"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/beta-data-heritrix"
      - "WAYBACK_URL_PREFIX=https://beta.webarchive.org.uk/act"

  w3act:
    environment:
      - "SERVER_NAME=https://beta.webarchive.org.uk"
      - "DB_URI=postgres://training:training@192.168.45.82/w3act"
      - "PII_URI=http://piiirc.ad.bl.uk/pii/vdc"
      - "ACCESS_RESOLVER_URI=https://beta.webarchive.org.uk/access/resolve/"

  # Disk volumes
  webrender:
    volumes:
      - "/zfspool/beta/webrender-tmp:/tmp/webrender"
  dvc:
    image: busybox
    volumes:
      - /zfspool/beta/heritrix/jobs:/jobs
      - /zfspool/beta/heritrix/scratch:/heritrix/scratch
      - /zfspool/beta/heritrix/state:/heritrix/state
      - /zfspool/beta/heritrix/output:/heritrix/output
      - /zfspool/beta/heritrix/wren:/heritrix/wren
      - /zfspool/beta/heritrix/task-state:/state
