version: '2'

services:
  # UKWA Heritrix
  ukwa-heritrix-daily:
    image: ukwa/heritrix
    hostname: ukwa-h3-pulse-daily
    ports:
      - "8443:8443"
    environment:
      - "HERITRIX_USER=${HERITRIX_USER}"
      - "HERITRIX_PW=${HERITRIX_PASSWORD}"
    #  - "MONITRIX_ENABLED=1"
    links:
      - clamd
      - amqp
      - webrender
    volumes:
      - jobs:/heritrix/jobs
      - output:/heritrix/output


  # Monitrix, built on ELK by extending Logstash to support Heritrix logs.
  monitrix:
    image: ukwa/monitrix
    ports:
      - "5601:5601"

  # RabbitMQ
  amqp:
    image: rabbitmq:3.5-management
    ports:
      - "15672:15672"  # management port (guest:guest)
    logging:
      driver: none  

  # PhantomJS web page rendering service
  webrender:
    image: webrender-phantomjs:2.0.0
    environment:
      - "WARCPROX=warcprox:8000"
    ports:
      - "8010:8010"
    links:
      - warcprox

  # WARC Proxy, with de-duplication disabled and a rapid rollover:
  warcprox:
    image: ukwa/warcprox
    command: "warcprox -b 0.0.0.0 -d /heritrix/wren --base32 -z --rollover-idle-time 60 -j /dev/null"
    ports:
      - "8000:8000"
    links:
      - openwayback
    ulimits:
      nproc: 65535 # See https://github.com/internetarchive/warcprox/blob/2.x/warcprox/warcproxy.py#L413
    volumes:
      - wren:/heritrix/wren
  

  # Other daemons and processes that coordinate the crawl
  shepherd:
    image: ukwa/python-shepherd
    environment:
      - "W3ACT_USER=${W3ACT_USER}"
      - "W3ACT_PW=${W3ACT_PASSWORD}"
      - "W3ACT_URL=https://beta.webarchive.org.uk/act/"
      - "HERITRIX_USER=${HERITRIX_USER}"
      - "HERITRIX_PW=${HERITRIX_PASSWORD}"
      - "CDXSERVER_URL=http://bigcdx.wa.bl.uk:8080/act2-beta"
      - "WAYBACK_URL=http://openwayback:8080/wayback"
      - "AMQP_URL=amqp://guest:guest@amqp:5672/%2f"
      - "QUEUE_NAME=FC-4-uris-to-index"
      - "PYTHONUNBUFFERED=TRUE"
    links:
      - amqp
      - ukwa-heritrix-daily
      - cdxserver
      - webrender
      - w3act
      - openwayback
      - monitrix
    ports:
      - "5001:8000"
      - "5082:8082"
    volumes:
      - jobs:/heritrix/jobs
      - output:/heritrix/output
      - wren:/heritrix/wren


  # OpenWayback, based loosely on UNB Libraries Dockerfile
  openwayback:
    image: ukwa/openwayback
    ports:
      - "9080:8080"
      - "8090:8090"
    environment:
      - "WAYBACK_URL_PREFIX=https://beta.webarchive.org.uk/act/wayback"
      - "CDX_INDEX_SERVER=http://bigcdx.wa.bl.uk:8080/act2-beta"
      - "WEBHDFS_PREFIX=http://hadoop.ddb.wa.bl.uk:14000/v1/webhdfs"

  # PDF to HTML service
  pdf2htmlex:
    image: ukwa/pdf2htmlex
    links:
      - openwayback

  # W3ACT
  w3act:
    image: uwka/w3act:2.0.0-BETA-4
    environment:
      - "SERVER_NAME=https://beta.webarchive.org.uk"
      - "APPLICATION_SECRET=${APPLICATION_SECRET}"
      - "SECRET_SERVER_USER=${SECRET_SERVER_USER}"
      - "SECRET_SERVER_PASSWORD=${SECRET_SERVER_PASSWORD}"
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URI=postgres://training:training@psql.beta.wa.bl.uk/w3act"
      - "USE_TEST_DATA=false"
      - "ENABLE_DDHAPT=true"
      - "PII_URI=http://piiirc.ad.bl.uk/pii/vdc"
      - "SMTP_SERVER=juno.bl.uk"
      - "WAYBACK_URL=http://openwayback:8080/wayback"
      - "MONITRIX_URI=http://monitrix:5601/app/kibana"
      - "PDFTOHTMLEX_UR=http://pdf2htmlex:5000/convert?url="
      - "AMQP_HOST=amqp"
      - "ACCESS_RESOLVER_URI=https://www.webarchive.org.uk/access/resolve/"
    ports:
      - "9000:9000"
    links:
      - openwayback
      - pdf2htmlex

volumes:
  # The location where we store the job data:
  - jobs:
  # The main crawler output location:
  - output:
  # Temporary output location for rendering pages:
  - wren:
