version: '2'

services:
  # UKWA Heritrix
  ukwa-heritrix-daily:
    image: ukwa/heritrix
    hostname: ukwa-h3-pulse-daily
    ports:
      - "${INTERNAL_IP}:8443:8443"
    environment:
      - "HERITRIX_USER=${HERITRIX_USER}"
      - "HERITRIX_PW=${HERITRIX_PASSWORD}"
    #  - "MONITRIX_ENABLED=1"
    links:
      - amqp
      - webrender
    volumes:
      - /zfspool/heritrix/jobs:/heritrix/jobs
      - /zfspool/heritrix/output:/heritrix/output


  # Monitrix, built on ELK by extending Logstash to support Heritrix logs.
  monitrix:
    image: ukwa/monitrix
    ports:
      - "${INTERNAL_IP}:5601:5601"

  # RabbitMQ
  amqp:
    image: rabbitmq:3.5-management
    ports:
      - "${INTERNAL_IP}:15672:15672"  # management port (guest:guest)
    logging:
      driver: none  

  # PhantomJS web page rendering service
  webrender:
    image: ukwa/webrender-phantomjs:2.0.0
    environment:
      - "WARCPROX=warcprox:8000"
#    ports:
#      - "${INTERNAL_IP}:8010:8010"
    links:
      - warcprox

  # WARC Proxy, with de-duplication disabled and a rapid rollover:
  warcprox:
    image: ukwa/warcprox
    command: "warcprox -b 0.0.0.0 -d /heritrix/wren --base32 -z --rollover-idle-time 60 -j /dev/null"
#    ports:
#      - "${INTERNAL_IP}:8000:8000"
    links:
      - openwayback
    ulimits:
      nproc: 65535 # See https://github.com/internetarchive/warcprox/blob/2.x/warcprox/warcproxy.py#L413
    volumes:
      - /zfspool/heritrix/wren:/heritrix/wren
  

  # Other daemons and processes that coordinate the crawl
  shepherd:
    image: ukwa/shepherd
    environment:
      - "W3ACT_USER=${W3ACT_USER}"
      - "W3ACT_PW=${W3ACT_PASSWORD}"
      - "W3ACT_URL=https://dev.webarchive.org.uk/act/"
      - "HERITRIX_USER=${HERITRIX_USER}"
      - "HERITRIX_PW=${HERITRIX_PASSWORD}"
      - "CDXSERVER_URL=http://192.168.45.21:8080/ddhapt-beta"
      - "WAYBACK_URL=http://openwayback:8080/wayback"
      - "AMQP_URL=amqp://guest:guest@amqp:5672/%2f"
      - "QUEUE_NAME=FC-4-uris-to-index"
      - "PYTHONUNBUFFERED=TRUE"
    links:
      - amqp
      - ukwa-heritrix-daily
      - webrender
      - w3act
      - openwayback
      - monitrix
#    ports:
#      - "${INTERNAL_IP}:5001:8000"
#      - "${INTERNAL_IP}:5082:8082"
    volumes:
      - /zfspool/heritrix/jobs:/heritrix/jobs
      - /zfspool/heritrix/output:/heritrix/output
      - /zfspool/heritrix/wren:/heritrix/wren


  # OpenWayback, based loosely on UNB Libraries Dockerfile
  openwayback:
    image: ukwa/openwayback
    ports:
      - "${INTERNAL_IP}:9080:8080"
#      - "${INTERNAL_IP}:8090:8090"
    environment:
      - "WAYBACK_URL_PREFIX=http://192.168.45.16:8080/act/wayback"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/act2-beta"
      - "WEBHDFS_PREFIX=http://192.168.45.43:14000/v1/webhdfs"

  # PDF to HTML service
  pdf2htmlex:
    image: ukwa/pdf2htmlex
    links:
      - openwayback

  # W3ACT
  w3act:
    image: ukwa/w3act:2.0.0-BETA-6
    environment:
      - "SERVER_NAME=https://dev.webarchive.org.uk"
      - "APPLICATION_SECRET=${APPLICATION_SECRET}"
      - "SECRET_SERVER_USER=${SECRET_SERVER_USER}"
      - "SECRET_SERVER_PASSWORD=${SECRET_SERVER_PASSWORD}"
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URI=postgres://training:training@192.168.45.82/w3act"
      - "USE_TEST_DATA=false"
      - "ENABLE_DDHAPT=true"
      - "PII_URI=http://piiirc.ad.bl.uk/pii/vdc"
      - "SMTP_SERVER=juno.bl.uk"
      - "WAYBACK_URL=http://openwayback:8080/wayback"
      - "MONITRIX_URI=http://monitrix:5601/app/kibana"
      - "PDFTOHTMLEX_URI=http://pdf2htmlex:5000/convert?url="
      - "AMQP_HOST=amqp"
      - "ACCESS_RESOLVER_URI=https://www.webarchive.org.uk/access/resolve/"
    command: "/w3act/target/universal/stage/bin/w3act -Dconfig.file=/w3act/conf/docker.conf -Dpidfile.path=/dev/null -Dhttp.proxyHost=explorer.bl.uk -Dhttp.proxyPort=3127 -Dhttps.proxyHost=explorer.bl.uk -Dhttps.proxyPort=3127 -Dhttp.nonProxyHosts=\"localhost|127.0.0.1|*.ad.bl.uk|*.wa.bl.uk|192.168.*\""
    ports:
      - "${INTERNAL_IP}:9000:9000"
    links:
      - openwayback
      - pdf2htmlex

#volumes:
  # The location where we store the job data:
#  - /zfspool/heritrix/jobs:/zfspool/heritrix/jobs
  # The main crawler output location:
#  - /zfspool/heritrix/output:/zfspool/heritrix/output
  # Temporary output location for rendering pages:
#  - /zfspool/heritrix/wren:/zfspool/heritrix/wren
