
version: '3.2'

services:

  # PostgreSQL for storing task state
  taskdb:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=ingest"
      - "POSTGRES_PASSWORD=ingest"
      - "POSTGRES_DB=ingest_task_state"
    ports:
      - "5432:5432"
    volumes:
      - "/data/ingest-task-db/postgresql:/var/lib/postgresql/data"
      - "/data/ingest-task-db/postgresql-in-out-box:/var/lib/postgresql/in-out-box"


