
version: "3.2"

services:

  # Our slightly-modified version of HttpFS:
  worker:
    image: ukwa/httpfs:cdh3u5
    user: tomcat
    volumes:
      - ./etc/hadoop:/etc/hadoop
    environment:
      - "SERVICE_PORTS=14000" # This is required so the dockercloud/haproxy knows what port to use
    networks:
      - httpfsnet
    extra_hosts:
      - "nellie:192.168.1.2"
    deploy:
      replicas: 3

  # HAProxy load balancer
  lb:
    image: dockercloud/haproxy
    ports:
      - "14000:80"
      - "1936:1936" # For monitoring/stats
    environment:
      - "BALANCE=roundrobin"
      - "TIMEOUT=connect 10s, client 1m, server 1m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - httpfsnet
    deploy: # There needs to be just one of these, located on a manager node so it can talk to Docker:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # Expose HAProxy stats in a form suitable for Prometheus:
  metrics:
    image: quay.io/prometheus/haproxy-exporter
    ports:
      - '9101:9101'
    command:
      - "--haproxy.scrape-uri=http://stats:stats@lb:1936/;csv"
    networks:
      - httpfsnet


# The auto-configuring HAProxy system appears to require that each proxied service runs in a dedicated virtual network
networks:
  httpfsnet:
    driver: overlay

