
version: '3.2'

services:

  # The WARChiving proxy itself
  warcprox-worker:
    image: ukwa/warcprox
    #command: "warcprox -b 0.0.0.0 -d /output/warcs --base32 -z --rollover-idle-time 3600 --dedup-db-file /dev/null --stats-db-file /dev/null --quiet --plugin warcprox-plugins.listeners.KafkaCaptureFeed --plugin warcprox-plugins.listeners.UpdateOutbackCDX 2>&1 | tee /output/log"
    command: "warcprox -b 0.0.0.0 -d /output/warcs --base32 -z --rollover-idle-time 3600 --dedup-db-file /dev/null --stats-db-file /dev/null"
    expose:
      - "8000"
    environment:
      - "EXCLUDE_PORTS=8888"
    volumes:
      - /data/test/warcproxen:/output/warcs
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"

  # HAProxy load balancer
  # https://github.com/docker/dockercloud-haproxy
  #
  # An auto-scaling frontend for multiple warcprox instances working together.
  # Seem to need the httpclose option to stop the proxy from dropping 'keep alive' connections
  warcprox:
    image: dockercloud/haproxy
    ports:
      - "3127:80"
      - "1936:1936"
    environment:
      - "BALANCE=hdr(host)"
      - "OPTION=redispatch,httpclose"
    links:
      - warcprox-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


