version: "3.2"

services:

  # ----------------------------------------------
  # QA Access
  # ----------------------------------------------
  warc-server:
    image: ukwa/warc-server
    ports:
      - 8001:8000
    environment:
      - "WARC_PATHS=/heritrix/output,/heritrix/wren,/previous/output,/previous/wren"
    volumes:
      - "/mnt/gluster/fc/heritrix/output:/heritrix/output"
      - "/mnt/gluster/fc/heritrix/wren:/heritrix/wren"
      - "/data/test/heritrix/output:/previous/output"
      - "/data/test/heritrix/wren:/previous/wren"

  # OpenWayback for QA
  openwayback:
    image: ukwa/waybacks
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=qa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://warc-server:8000/by-filename/"
      - "CDX_INDEX_SERVER=http://192.168.45.21:9090/fc"
      - "WAYBACK_URL_PREFIX=http://crawler02.bl.uk:8080"
      - "WAYBACK_URL_HOST=crawler02.bl.uk"

