# This override file augments the base configuration with the additional configuration that distingiuishes different deployments
#
# The settings below are for the 'prod' service.
#
version: '2'

services:

  # Integration points:
  shepherd:
    environment:
      - "CDXSERVER_URL=http://192.168.45.21:8080/data-heritrix"
      - "HDFS_OUTPUT_PREFIX=/"
      - "HDFS_NAMENODE_HOST=192.168.45.13"
      - "HDFS_NAMENODE_PORT=50070"
      - "HDFS_EFFECTIVE_USER=heritrix"
      - "WEBHDFS_PORT=14000"
      - "WEBHDFS_USER=heritrix"
      - "WEBHDFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"

  openwayback:
    environment:
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/data-heritrix"
      - "WAYBACK_URL_PREFIX=https://www.webarchive.org.uk/act"

  w3act:
    environment:
      - "SERVER_NAME=https://www.webarchive.org.uk"
      - "PII_URI=http://pii.ad.bl.uk/pii/vdc"
      - "ACCESS_RESOLVER_URI=https://www.webarchive.org.uk/access/resolve/"
      - "ENABLE_EVOLUTIONS=false"
      - "APPLY_EVOLUTIONS=false"
      - "APPLY_DOWN_EVOLUTIONS=false" # WARNING DOWNS ARE POTENTIALLY DESTRUCTIVE

  # Disk volumes for individual services:
  postgres:
    volumes:
      - "/zfspool/prod/postgresql:/var/lib/postgresql/data"

  warcprox:
    volumes:
      - "/zfspool/test/tmp/warcprox:/tmp/warcprox"

  webrender:
    volumes:
      - "/zfspool/prod/webrender-tmp:/tmp/webrender"
      - "./gunicorn.ini:/webrender/gunicorn.ini" # Override render server configuration

  # Data Volume Container (as explicit volumes are not okay for production. 
  #  not clear why, see http://serverfault.com/questions/750868/how-to-decide-between-a-docker-volume-container-and-a-docker-volume)
  # Should probably switch to named volumes (below)
  dvc:
    image: busybox
    volumes:
      - /zfspool/prod/heritrix/jobs:/jobs
      - /zfspool/prod/heritrix/scratch:/heritrix/scratch
      - /zfspool/prod/heritrix/state:/heritrix/state
      - /zfspool/prod/heritrix/output:/heritrix/output
      - /zfspool/prod/heritrix/wren:/heritrix/wren
      - /zfspool/prod/heritrix/task-state:/state
