# This override file augments the base configuration with the additional configuration that distingiuishes different deployments
#
# The settings below are for the 'dev' service.
#
version: '2'

services:

  # Integration points:
  shepherd:
    environment:
      - "CDXSERVER_URL=http://192.168.45.21:8080/ddhapt-beta"
      - "HDFS_OUTPUT_PREFIX=/"
      - "HDFS_NAMENODE_HOST=192.168.45.43"
      - "HDFS_NAMENODE_PORT=50070"
      - "HDFS_EFFECTIVE_USER=hdfs"
      - "WEBHDFS_PORT=14000"
      - "WEBHDFS_USER=hdfs"
      - "WEBHDFS_PREFIX=http://192.168.45.43:14000/webhdfs/v1"

  openwayback:
    environment:
      - "WAYBACK_HTTPFS_PREFIX=http://192.168.45.43:14000/webhdfs/v1"
      - "CDX_INDEX_SERVER=http://192.168.45.21:8080/ddhapt-beta"
      - "WAYBACK_URL_PREFIX=https://dev.webarchive.org.uk/act"

  w3act:
    environment:
      - "SERVER_NAME=https://dev.webarchive.org.uk"
      - "PII_URI=http://piiirc.ad.bl.uk/pii/vdc"
      - "ACCESS_RESOLVER_URI=https://dev.webarchive.org.uk/access/resolve/"
      - "DB_URI=postgres://training:training@192.168.45.82/w3act"

  # Disk volumes for individual services:
  postgres:
    volumes:
      - "/zfspool/postgresql:/var/lib/postgresql/data"

  warcprox:
    volumes:
      - "/zfspool/test/tmp/warcprox:/tmp-warcprox"

  webrender:
    #environment:
    #  - "WARCPROX="
    volumes:
      - "/zfspool/test/tmp/webrender:/tmp-webrender"
      - "./gunicorn.ini:/webrender/gunicorn.ini"

  # Data Volume Container (as explicit volumes are not okay for production. 
  #  not clear why, see http://serverfault.com/questions/750868/how-to-decide-between-a-docker-volume-container-and-a-docker-volume)
  # Should probably switch to named volumes (below)
  dvc:
    image: busybox
    volumes:
      - /zfspool/test/heritrix/jobs:/jobs
      - /zfspool/test/heritrix/scratch:/heritrix/scratch
      - /zfspool/test/heritrix/state:/heritrix/state
      - /zfspool/test/heritrix/output:/heritrix/output
      - /zfspool/test/heritrix/wren:/heritrix/wren
      - /zfspool/test/heritrix/task-state:/state
