# This override file augments the base configuration with the additional configuration that distingiuishes different deployments
#
# The settings below are for the 'prod' service.
#
version: '2'

services:

  # Integration points:
  shepherd:
    environment:
      - "W3ACT_URL=http://crawler03.bl.uk:9000/act/"
      - "WAYBACK_URL=http://wayback:8080/wayback"
      - "CDXSERVER_URL=http://bigcdx:8080/data-heritrix"
      - "HDFS_OUTPUT_PREFIX=/"
      - "HDFS_NAMENODE_HOST=nellie"
      - "HDFS_NAMENODE_PORT=50070"
      - "HDFS_EFFECTIVE_USER=heritrix"
      - "WEBHDFS_PORT=14000"
      - "WEBHDFS_USER=heritrix"
      - "WEBHDFS_PREFIX=http://hdfs:14000/webhdfs/v1"
    extra_hosts:
      - "wayback:194.66.232.89"

  # Disk volumes for individual services:
  warcprox:
    volumes:
      - "/data/prod/tmp/warcprox:/tmp/warcprox"

  webrender:
    volumes:
      - "/data/prod/webrender-tmp:/tmp/webrender"
      - "./gunicorn.ini:/webrender/gunicorn.ini" # Override render server configuration

  # Data Volume Container (as explicit volumes are not okay for production. 
  #  not clear why, see http://serverfault.com/questions/750868/how-to-decide-between-a-docker-volume-container-and-a-docker-volume)
  # Should probably switch to named volumes (below)
  dvc:
    image: busybox
    volumes:
      - /data/prod/heritrix/jobs:/jobs
      - /data/prod/heritrix/scratch:/heritrix/scratch
      - /data/prod/heritrix/state:/heritrix/state
      - /data/prod/heritrix/output:/heritrix/output
      - /data/prod/heritrix/wren:/heritrix/wren
      - /data/prod/heritrix/task-state:/state

  # Add monitoring hook:
  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.3
    volumes:
      - '${PWD}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    volumes_from:
      - dvc:rw
    extra_hosts:
      - "logstash:192.168.45.19"

  # Exporter for Prometheus
  heritrix3-exporter:
    image: ukwa/heritrix3-exporter
    ports:
      - 9118:9118
    environment:
      - "HERITRIX_USER=admin"
      - "HERITRIX_PASSWORD=bl_uk"
    extra_hosts:
      - "crawler01.bl.uk:192.168.45.16"
      - "crawler02.bl.uk:192.168.45.19"
      - "crawler03.bl.uk:192.168.45.28"
      - "crawler04.bl.uk:192.168.45.12"
    volumes:
      - '${PWD}/crawl-jobs.json:/monitor/crawl-jobs.json'

